name = "Solworld"
author = "Snowriter"
version = "0.1.0.21"
description = "Ciallo～(∠・ω< )⌒☆ 欢迎来到 Solworld！祝你在这个世界玩得开心！"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70beed69c0369222c2d08372dd460fb7cdd3b1ca0bb9d0f93d9caad5907ea31f"

[versions]
fabric = "0.18.4"
java = "21"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3"]
