name = "Solworld"
author = "Snowriter"
version = "1.0.0"
description = "一个精心优化的 1.21.1 生存整合包。内置高性能渲染配置与基础生存增强，开箱即用。"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fef550ae7f7105045bd3fa42fe81a8ca146b23ff01b1a6df35b25e740eeba3e"

[versions]
fabric = "0.18.4"
java = "21"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.4", "1.20.6", "1.21", "1.21.1", "1.21.2", "1.21.3"]
