name = "solworld"
author = "Snowriter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb8f871dcd174eb13359c20cd67fa3f9b671e2a6e62cb00dee85c241e0ed94af"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
