name = "Solworld"
author = "Snowriter"
version = "0.1.0.73"
description = "Ciallo～(∠・ω< )⌒☆ 欢迎来到 Solworld！祝你在这个世界玩得开心！"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c73fe5426029c25ef3b2b10b72275f4815e2c01763751d825c5c43c17c70c09"

[versions]
fabric = "0.18.4"
java = "21"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3"]
datapack-folder = "datapacks"
