name = "Solworld"
author = "Snowriter"
version = "0.1.0.44"
description = "Ciallo～(∠・ω< )⌒☆ 欢迎来到 Solworld！祝你在这个世界玩得开心！"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "486373b98977ba2e19d89338782e35f2a86296b7310a9233b436f5bdfffa2c8e"

[versions]
fabric = "0.18.4"
java = "21"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3"]
datapack-folder = "datapacks"
