name = "Solworld"
author = "Snowriter"
version = "0.1.0.55"
description = "Ciallo～(∠・ω< )⌒☆ 欢迎来到 Solworld！祝你在这个世界玩得开心！"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d67b33b020fcc35f174127efdac3abff3bec0b5379f151f9ecd560c1d086911"

[versions]
fabric = "0.18.4"
java = "21"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3"]
datapack-folder = "datapacks"
