name = "Solworld"
author = "Snowriter"
version = "0.1.0.50"
description = "Ciallo～(∠・ω< )⌒☆ 欢迎来到 Solworld！祝你在这个世界玩得开心！"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c77df00421c5ec6d6e2258f0ecc67fad96b799eeecb9a49330f5ebc1e6cbe1a"

[versions]
fabric = "0.18.4"
java = "21"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3"]
datapack-folder = "datapacks"
